In [2]:
import numpy as np
 
import time
import sys

S= range(1000)
print("list: ", sys.getsizeof(5)*len(S))
 
D= np.arange(1000)
print("NumPy Array: ", D.size*D.itemsize)

list:  28000
NumPy Array:  8000


In [4]:
import time
import sys
 
SIZE = 1000000
L1= range(SIZE)
L2= range(SIZE)

A1= np.arange(SIZE)
A2=np.arange(SIZE)
 
start= time.time()
result=[x+y for x,y in zip(L1,L2)]
print((time.time()-start)*1000)
 
start=time.time()
result= A1+A2
print((time.time()-start)*1000)

117.5391674041748
15.264272689819336


In [7]:
import numpy as np
data = np.random.randn(2, 3)
data

array([[-0.28946346, -1.88504934, -1.0870331 ],
       [ 0.76671101,  0.12650437, -0.08366826]])

In [8]:
data * 10

array([[ -2.89463456, -18.85049342, -10.87033097],
       [  7.66711008,   1.26504369,  -0.83668257]])

In [9]:
data + data

array([[-0.57892691, -3.77009868, -2.17406619],
       [ 1.53342202,  0.25300874, -0.16733651]])

In [11]:
data.shape

(2, 3)

In [14]:
x = np.arange(4)
print("x =", x)
print("x + 5 =", x + 5) 
print("x - 5 =", x - 5) 
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2) # floor division

x = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [ 0.   0.5  1.   1.5]
x // 2 = [0 0 1 1]


In [16]:
print("-x = ", -x) 
print("x ** 2 = ", x ** 2)
print("x % 2 = ", x % 2)

-x =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2 =  [0 1 0 1]


In [18]:
-(0.5*x + 1) ** 2

array([-1.  , -2.25, -4.  , -6.25])

In [20]:
theta = np.linspace(0, np.pi, 3)

print("theta = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta =  [ 0.          1.57079633  3.14159265]
sin(theta) =  [  0.00000000e+00   1.00000000e+00   1.22464680e-16]
cos(theta) =  [  1.00000000e+00   6.12323400e-17  -1.00000000e+00]
tan(theta) =  [  0.00000000e+00   1.63312394e+16  -1.22464680e-16]


In [21]:
x = [1, 2, 3] 
print("x =", x)
print("e^x =",np.exp(x)) 
print("2^x =",np.exp2(x)) 
print("3^x =",np.power(3,x))

x = [1, 2, 3]
e^x = [  2.71828183   7.3890561   20.08553692]
2^x = [ 2.  4.  8.]
3^x = [ 3  9 27]


In [22]:
x = [1, 2, 4, 10] 

print("x =", x)
print("ln(x) =", np.log(x)) 
print("log2(x) =", np.log2(x)) 
print("log10(x) =", np.log10(x))

x = [1, 2, 4, 10]
ln(x) = [ 0.          0.69314718  1.38629436  2.30258509]
log2(x) = [ 0.          1.          2.          3.32192809]
log10(x) = [ 0.          0.30103     0.60205999  1.        ]
